import type { ExerciseSeed } from "../types";

/**
 * Core, loaded carries, and conditioning/cardio modalities.
 *
 * Core work is split by *function* rather than lumped as "abs": anti-extension,
 * anti-rotation, flexion and lateral flexion train different things, and a
 * program that only does crunches has a hole in it.
 *
 * Conditioning entries use `time`, `distance` or `calories` load types, which is
 * what tells the logger to show a stopwatch instead of a weight field.
 */

export const CORE: ExerciseSeed[] = [
  {
    slug: "plank",
    name: "Plank",
    pattern: "core_anti_extension",
    primary: ["abs"],
    secondary: ["obliques", "glutes"],
    equipment: ["bodyweight"],
    load: "time",
    complexity: 1,
    sfr: 4,
    reps: [1, 1],
    sub: "anti-extension",
    cues: "Squeeze glutes, tuck the ribs, brace hard. If you can hold it three minutes, make it harder rather than longer.",
  },
  {
    slug: "rkc-plank",
    name: "RKC Plank",
    pattern: "core_anti_extension",
    primary: ["abs"],
    secondary: ["obliques", "glutes"],
    equipment: ["bodyweight"],
    load: "time",
    complexity: 2,
    sfr: 5,
    reps: [1, 1],
    sub: "anti-extension",
    cues: "Maximal full-body tension. Ten to twenty seconds is a working set.",
  },
  {
    slug: "ab-wheel-rollout",
    name: "Ab Wheel Rollout",
    pattern: "core_anti_extension",
    primary: ["abs"],
    secondary: ["obliques", "lats"],
    equipment: ["ab_wheel"],
    load: "bodyweight",
    complexity: 3,
    sfr: 4,
    reps: [6, 15],
    sub: "anti-extension",
    cues: "Do not let the lower back arch. Shorten the range before you let form go.",
  },
  {
    slug: "dead-bug",
    name: "Dead Bug",
    pattern: "core_anti_extension",
    primary: ["abs"],
    equipment: ["bodyweight"],
    load: "reps_only",
    complexity: 1,
    sfr: 5,
    reps: [8, 20],
    sub: "anti-extension",
  },
  {
    slug: "hollow-hold",
    name: "Hollow Hold",
    pattern: "core_anti_extension",
    primary: ["abs"],
    secondary: ["obliques"],
    equipment: ["bodyweight"],
    load: "time",
    complexity: 2,
    sfr: 4,
    reps: [1, 1],
    sub: "anti-extension",
  },
  {
    slug: "bird-dog",
    name: "Bird Dog",
    pattern: "core_anti_rotation",
    primary: ["abs"],
    secondary: ["lower_back", "glutes"],
    equipment: ["bodyweight"],
    load: "reps_only",
    complexity: 1,
    sfr: 5,
    reps: [8, 16],
    sub: "anti-rotation",
  },
  {
    slug: "cable-pallof-press",
    name: "Cable Pallof Press",
    pattern: "core_anti_rotation",
    primary: ["obliques", "abs"],
    equipment: ["cable_machine"],
    load: "cable_load",
    complexity: 2,
    sfr: 5,
    reps: [10, 20],
    sub: "anti-rotation",
    cues: "The whole point is that nothing rotates. Resist, don't twist.",
  },
  {
    slug: "band-pallof-press",
    name: "Band Pallof Press",
    pattern: "core_anti_rotation",
    primary: ["obliques", "abs"],
    equipment: ["resistance_band_long"],
    load: "band",
    complexity: 1,
    sfr: 5,
    reps: [12, 25],
    sub: "anti-rotation",
  },
  {
    slug: "side-plank",
    name: "Side Plank",
    pattern: "core_lateral_flexion",
    primary: ["obliques"],
    secondary: ["abs", "abductors"],
    equipment: ["bodyweight"],
    load: "time",
    unilateral: true,
    complexity: 1,
    sfr: 5,
    reps: [1, 1],
    sub: "lateral-flexion",
  },
  {
    slug: "dumbbell-side-bend",
    name: "Dumbbell Side Bend",
    pattern: "core_lateral_flexion",
    primary: ["obliques"],
    secondary: ["abs"],
    equipment: ["dumbbell"],
    load: "dumbbell_single",
    unilateral: true,
    complexity: 1,
    sfr: 5,
    reps: [12, 20],
    sub: "lateral-flexion",
  },
  {
    slug: "hanging-leg-raise",
    name: "Hanging Leg Raise",
    pattern: "core_flexion",
    primary: ["abs"],
    secondary: ["obliques", "forearms"],
    equipment: ["pullup_bar"],
    load: "bodyweight",
    complexity: 3,
    sfr: 4,
    reps: [6, 15],
    sub: "trunk-flexion",
    cues: "Curl the pelvis under rather than just swinging the legs up.",
  },
  {
    slug: "hanging-knee-raise",
    name: "Hanging Knee Raise",
    pattern: "core_flexion",
    primary: ["abs"],
    secondary: ["obliques"],
    equipment: ["pullup_bar"],
    load: "bodyweight",
    complexity: 2,
    sfr: 4,
    reps: [8, 20],
    sub: "trunk-flexion",
  },
  {
    slug: "cable-crunch",
    name: "Cable Crunch",
    pattern: "core_flexion",
    primary: ["abs"],
    equipment: ["cable_machine"],
    load: "cable_load",
    complexity: 1,
    sfr: 5,
    reps: [10, 20],
    sub: "trunk-flexion",
    cues: "One of the few ways to load trunk flexion progressively.",
  },
  {
    slug: "reverse-crunch",
    name: "Reverse Crunch",
    pattern: "core_flexion",
    primary: ["abs"],
    equipment: ["bodyweight"],
    load: "bodyweight",
    complexity: 1,
    sfr: 5,
    reps: [10, 25],
    sub: "trunk-flexion",
  },
  {
    slug: "v-up",
    name: "V-Up",
    pattern: "core_flexion",
    primary: ["abs"],
    secondary: ["quads"],
    equipment: ["bodyweight"],
    load: "bodyweight",
    complexity: 2,
    sfr: 4,
    reps: [8, 20],
    sub: "trunk-flexion",
  },
  {
    slug: "l-sit",
    name: "L-Sit",
    pattern: "core_flexion",
    primary: ["abs"],
    secondary: ["quads", "triceps"],
    equipment: ["bodyweight"],
    optional: ["dip_bars", "gymnastic_rings"],
    load: "time",
    complexity: 4,
    sfr: 4,
    reps: [1, 1],
    sub: "trunk-flexion",
  },
];

export const CARRIES: ExerciseSeed[] = [
  {
    slug: "farmer-carry",
    name: "Farmer Carry",
    pattern: "carry",
    primary: ["forearms", "traps"],
    secondary: ["abs", "obliques", "upper_back", "quads"],
    equipment: ["dumbbell"],
    load: "distance",
    complexity: 1,
    sfr: 4,
    reps: [1, 1],
    sub: "loaded-carry",
    cues: "Tall posture, ribs down. Progress by load or distance.",
  },
  {
    slug: "suitcase-carry",
    name: "Suitcase Carry",
    pattern: "carry",
    primary: ["obliques", "forearms"],
    secondary: ["abs", "traps", "abductors"],
    equipment: ["dumbbell"],
    load: "distance",
    unilateral: true,
    complexity: 1,
    sfr: 5,
    reps: [1, 1],
    sub: "loaded-carry",
    cues: "Loaded on one side only, so the obliques work hard to stop you tipping.",
  },
  {
    slug: "front-rack-carry",
    name: "Front Rack Carry",
    pattern: "carry",
    primary: ["abs", "upper_back"],
    secondary: ["traps", "front_delts"],
    equipment: ["kettlebell"],
    load: "distance",
    complexity: 2,
    sfr: 4,
    reps: [1, 1],
    sub: "loaded-carry",
  },
  {
    slug: "overhead-carry",
    name: "Overhead Carry",
    pattern: "carry",
    primary: ["front_delts", "abs"],
    secondary: ["traps", "upper_back"],
    equipment: ["kettlebell"],
    load: "distance",
    complexity: 3,
    sfr: 4,
    reps: [1, 1],
    sub: "loaded-carry",
  },
  {
    slug: "sled-push",
    name: "Sled Push",
    pattern: "carry",
    primary: ["quads", "glutes"],
    secondary: ["calves", "abs"],
    equipment: ["sled"],
    load: "distance",
    complexity: 1,
    sfr: 4,
    reps: [1, 1],
    sub: "sled",
    cues: "Almost no eccentric, so it builds work capacity without much soreness.",
  },
  {
    slug: "sled-drag",
    name: "Sled Drag",
    pattern: "carry",
    primary: ["quads", "glutes", "hamstrings"],
    secondary: ["upper_back", "forearms"],
    equipment: ["sled"],
    load: "distance",
    complexity: 1,
    sfr: 4,
    reps: [1, 1],
    sub: "sled",
  },
];

export const CONDITIONING: ExerciseSeed[] = [
  {
    slug: "air-bike",
    name: "Air Bike",
    aliases: ["assault bike", "echo bike"],
    pattern: "conditioning",
    primary: ["quads", "glutes"],
    secondary: ["hamstrings", "front_delts", "lats"],
    equipment: ["air_bike"],
    load: "calories",
    complexity: 1,
    sfr: 3,
    reps: [1, 1],
    sub: "erg-conditioning",
    cues: "Brutally effective for intervals. Resistance scales with effort, so it self-regulates.",
  },
  {
    slug: "rowing-machine",
    name: "Rowing Machine",
    aliases: ["erg", "rower", "concept 2"],
    pattern: "conditioning",
    primary: ["lats", "quads", "glutes"],
    secondary: ["upper_back", "hamstrings", "biceps"],
    equipment: ["rower"],
    load: "distance",
    complexity: 2,
    sfr: 4,
    reps: [1, 1],
    sub: "erg-conditioning",
    cues: "Legs, then back, then arms. Reverse it on the recovery.",
  },
  {
    slug: "ski-erg",
    name: "Ski Erg",
    pattern: "conditioning",
    primary: ["lats", "abs"],
    secondary: ["triceps", "glutes"],
    equipment: ["ski_erg"],
    load: "distance",
    complexity: 2,
    sfr: 4,
    reps: [1, 1],
    sub: "erg-conditioning",
  },
  {
    slug: "stationary-bike",
    name: "Stationary Bike",
    pattern: "conditioning",
    primary: ["quads"],
    secondary: ["glutes", "hamstrings", "calves"],
    equipment: ["stationary_bike"],
    load: "time",
    complexity: 1,
    sfr: 5,
    reps: [1, 1],
    sub: "low-impact-cardio",
    cues: "The lowest-interference cardio option — least likely to blunt lifting progress.",
  },
  {
    slug: "treadmill-run",
    name: "Treadmill Run",
    pattern: "conditioning",
    primary: ["quads", "hamstrings", "calves"],
    secondary: ["glutes"],
    equipment: ["treadmill"],
    load: "distance",
    complexity: 1,
    sfr: 3,
    reps: [1, 1],
    sub: "running",
  },
  {
    slug: "treadmill-incline-walk",
    name: "Incline Treadmill Walk",
    pattern: "conditioning",
    primary: ["glutes", "calves"],
    secondary: ["quads", "hamstrings"],
    equipment: ["treadmill"],
    load: "time",
    complexity: 1,
    sfr: 5,
    reps: [1, 1],
    sub: "low-impact-cardio",
    cues: "High calorie burn, minimal interference with strength work. The default fat-loss cardio.",
  },
  {
    slug: "outdoor-run",
    name: "Outdoor Run",
    pattern: "conditioning",
    primary: ["quads", "hamstrings", "calves"],
    secondary: ["glutes"],
    equipment: ["bodyweight"],
    load: "distance",
    complexity: 1,
    sfr: 3,
    reps: [1, 1],
    sub: "running",
  },
  {
    slug: "outdoor-walk",
    name: "Walk",
    pattern: "conditioning",
    primary: ["calves", "glutes"],
    equipment: ["bodyweight"],
    load: "distance",
    complexity: 1,
    sfr: 5,
    reps: [1, 1],
    sub: "low-impact-cardio",
  },
  {
    slug: "stair-climber",
    name: "Stair Climber",
    pattern: "conditioning",
    primary: ["glutes", "quads"],
    secondary: ["calves", "hamstrings"],
    equipment: ["stair_climber"],
    load: "time",
    complexity: 1,
    sfr: 4,
    reps: [1, 1],
    sub: "low-impact-cardio",
  },
  {
    slug: "elliptical",
    name: "Elliptical",
    pattern: "conditioning",
    primary: ["quads", "glutes"],
    secondary: ["hamstrings", "calves"],
    equipment: ["elliptical"],
    load: "time",
    complexity: 1,
    sfr: 5,
    reps: [1, 1],
    sub: "low-impact-cardio",
  },
  {
    slug: "jump-rope",
    name: "Jump Rope",
    pattern: "conditioning",
    primary: ["calves"],
    secondary: ["quads", "forearms"],
    equipment: ["jump_rope"],
    load: "time",
    complexity: 2,
    sfr: 4,
    reps: [1, 1],
    sub: "portable-conditioning",
    cues: "Packs into a suitcase and needs two metres of floor. Ideal travel conditioning.",
  },
  {
    slug: "burpee",
    name: "Burpee",
    pattern: "conditioning",
    primary: ["quads", "chest"],
    secondary: ["glutes", "triceps", "abs"],
    equipment: ["bodyweight"],
    load: "reps_only",
    complexity: 2,
    sfr: 3,
    reps: [8, 25],
    sub: "portable-conditioning",
  },
  {
    slug: "mountain-climber",
    name: "Mountain Climber",
    pattern: "conditioning",
    primary: ["abs"],
    secondary: ["quads", "front_delts"],
    equipment: ["bodyweight"],
    load: "time",
    complexity: 1,
    sfr: 4,
    reps: [1, 1],
    sub: "portable-conditioning",
  },
  {
    slug: "high-knees",
    name: "High Knees",
    pattern: "conditioning",
    primary: ["quads", "calves"],
    secondary: ["abs"],
    equipment: ["bodyweight"],
    load: "time",
    complexity: 1,
    sfr: 4,
    reps: [1, 1],
    sub: "portable-conditioning",
  },
  {
    slug: "battle-ropes",
    name: "Battle Ropes",
    pattern: "conditioning",
    primary: ["front_delts", "abs"],
    secondary: ["forearms", "upper_back"],
    equipment: ["battle_ropes"],
    load: "time",
    complexity: 1,
    sfr: 4,
    reps: [1, 1],
    sub: "erg-conditioning",
  },
  {
    slug: "kettlebell-thruster",
    name: "Kettlebell Thruster",
    pattern: "conditioning",
    primary: ["quads", "front_delts"],
    secondary: ["glutes", "triceps", "abs"],
    equipment: ["kettlebell"],
    load: "kettlebell",
    compound: true,
    complexity: 3,
    sfr: 3,
    reps: [8, 20],
    sub: "portable-conditioning",
  },
  {
    slug: "dumbbell-thruster",
    name: "Dumbbell Thruster",
    pattern: "conditioning",
    primary: ["quads", "front_delts"],
    secondary: ["glutes", "triceps"],
    equipment: ["dumbbell"],
    load: "dumbbell_pair",
    compound: true,
    complexity: 3,
    sfr: 3,
    reps: [8, 20],
    sub: "portable-conditioning",
  },
  {
    slug: "devil-press",
    name: "Devil Press",
    pattern: "conditioning",
    primary: ["glutes", "front_delts"],
    secondary: ["hamstrings", "chest", "abs"],
    equipment: ["dumbbell"],
    load: "dumbbell_pair",
    compound: true,
    complexity: 4,
    sfr: 2,
    reps: [6, 15],
    sub: "portable-conditioning",
  },
  {
    slug: "shuttle-run",
    name: "Shuttle Run",
    pattern: "conditioning",
    primary: ["quads", "glutes"],
    secondary: ["calves", "hamstrings"],
    equipment: ["bodyweight"],
    load: "time",
    complexity: 1,
    sfr: 3,
    reps: [1, 1],
    sub: "portable-conditioning",
  },
];

export const CORE_CONDITIONING: ExerciseSeed[] = [...CORE, ...CARRIES, ...CONDITIONING];
