import type { ExerciseSeed } from "../types";

/**
 * Single-joint work: arms, delts, traps, calves and the machine-isolation lifts.
 *
 * These carry high stimulus-to-fatigue ratings by design. When the engine is
 * squeezed for time it drops isolation before compounds, but when weekly volume
 * for a lagging muscle needs topping up cheaply, this is where it comes from.
 */

export const ARMS: ExerciseSeed[] = [
  {
    slug: "barbell-curl",
    name: "Barbell Curl",
    pattern: "isolation_upper",
    primary: ["biceps"],
    secondary: ["forearms"],
    equipment: ["barbell", "weight_plate"],
    load: "barbell",
    complexity: 1,
    sfr: 4,
    reps: [6, 12],
    sub: "biceps-curl",
  },
  {
    slug: "ez-bar-curl",
    name: "EZ-Bar Curl",
    pattern: "isolation_upper",
    primary: ["biceps"],
    secondary: ["forearms"],
    equipment: ["ez_bar", "weight_plate"],
    load: "barbell",
    complexity: 1,
    sfr: 5,
    reps: [8, 15],
    sub: "biceps-curl",
    cues: "Kinder to the wrists than a straight bar.",
  },
  {
    slug: "dumbbell-curl",
    name: "Dumbbell Curl",
    pattern: "isolation_upper",
    primary: ["biceps"],
    secondary: ["forearms"],
    equipment: ["dumbbell"],
    load: "dumbbell_pair",
    complexity: 1,
    sfr: 5,
    reps: [8, 15],
    sub: "biceps-curl",
  },
  {
    slug: "dumbbell-hammer-curl",
    name: "Hammer Curl",
    pattern: "isolation_upper",
    primary: ["biceps", "forearms"],
    equipment: ["dumbbell"],
    load: "dumbbell_pair",
    complexity: 1,
    sfr: 5,
    reps: [8, 15],
    sub: "biceps-curl",
  },
  {
    slug: "dumbbell-incline-curl",
    name: "Incline Dumbbell Curl",
    pattern: "isolation_upper",
    primary: ["biceps"],
    equipment: ["dumbbell", "bench_adjustable"],
    load: "dumbbell_pair",
    complexity: 1,
    sfr: 5,
    reps: [8, 15],
    sub: "biceps-curl",
    cues: "Trains the biceps in a stretched position, which the standing curl misses.",
  },
  {
    slug: "preacher-curl",
    name: "Preacher Curl",
    pattern: "isolation_upper",
    primary: ["biceps"],
    equipment: ["preacher_curl_bench", "ez_bar", "weight_plate"],
    load: "barbell",
    complexity: 1,
    sfr: 5,
    reps: [8, 15],
    sub: "biceps-curl",
  },
  {
    slug: "cable-curl",
    name: "Cable Curl",
    pattern: "isolation_upper",
    primary: ["biceps"],
    equipment: ["cable_machine"],
    load: "cable_load",
    complexity: 1,
    sfr: 5,
    reps: [10, 15],
    sub: "biceps-curl",
  },
  {
    slug: "band-curl",
    name: "Band Curl",
    pattern: "isolation_upper",
    primary: ["biceps"],
    equipment: ["resistance_band_long"],
    load: "band",
    complexity: 1,
    sfr: 5,
    reps: [12, 25],
    sub: "biceps-curl",
  },
  {
    slug: "barbell-skullcrusher",
    name: "Skullcrusher",
    aliases: ["lying triceps extension"],
    pattern: "isolation_upper",
    primary: ["triceps"],
    equipment: ["ez_bar", "weight_plate", "bench_flat"],
    load: "barbell",
    complexity: 2,
    sfr: 4,
    reps: [8, 15],
    sub: "triceps-extension",
  },
  {
    slug: "dumbbell-overhead-triceps-extension",
    name: "Overhead Triceps Extension",
    pattern: "isolation_upper",
    primary: ["triceps"],
    equipment: ["dumbbell"],
    load: "dumbbell_single",
    complexity: 1,
    sfr: 5,
    reps: [10, 15],
    sub: "triceps-extension",
    cues: "Overhead puts the long head under stretch, which pushdowns barely touch.",
  },
  {
    slug: "cable-overhead-triceps-extension",
    name: "Cable Overhead Triceps Extension",
    pattern: "isolation_upper",
    primary: ["triceps"],
    equipment: ["cable_machine"],
    load: "cable_load",
    complexity: 2,
    sfr: 5,
    reps: [10, 15],
    sub: "triceps-extension",
  },
  {
    slug: "cable-triceps-pushdown",
    name: "Cable Triceps Pushdown",
    pattern: "isolation_upper",
    primary: ["triceps"],
    equipment: ["cable_machine"],
    load: "cable_load",
    complexity: 1,
    sfr: 5,
    reps: [10, 20],
    sub: "triceps-pushdown",
  },
  {
    slug: "band-triceps-pushdown",
    name: "Band Triceps Pushdown",
    pattern: "isolation_upper",
    primary: ["triceps"],
    equipment: ["resistance_band_long"],
    load: "band",
    complexity: 1,
    sfr: 5,
    reps: [15, 25],
    sub: "triceps-pushdown",
  },
  {
    slug: "bench-dip",
    name: "Bench Dip",
    pattern: "isolation_upper",
    primary: ["triceps"],
    secondary: ["front_delts", "chest"],
    equipment: ["bodyweight", "bench_or_chair"],
    load: "bodyweight",
    complexity: 1,
    sfr: 4,
    reps: [10, 25],
    sub: "triceps-pushdown",
  },
  {
    slug: "dumbbell-wrist-curl",
    name: "Wrist Curl",
    pattern: "isolation_upper",
    primary: ["forearms"],
    equipment: ["dumbbell"],
    load: "dumbbell_pair",
    complexity: 1,
    sfr: 5,
    reps: [12, 25],
    sub: "forearm-isolation",
  },
  {
    slug: "dead-hang",
    name: "Dead Hang",
    pattern: "isolation_upper",
    primary: ["forearms"],
    secondary: ["lats", "traps"],
    equipment: ["pullup_bar"],
    load: "time",
    complexity: 1,
    sfr: 5,
    reps: [1, 1],
    sub: "forearm-isolation",
    cues: "Grip work plus a decongestant for the shoulders. Progress in seconds.",
  },
];

export const DELTS_TRAPS: ExerciseSeed[] = [
  {
    slug: "dumbbell-lateral-raise",
    name: "Dumbbell Lateral Raise",
    aliases: ["side raise", "lateral raise"],
    pattern: "isolation_upper",
    primary: ["side_delts"],
    equipment: ["dumbbell"],
    load: "dumbbell_pair",
    complexity: 1,
    sfr: 5,
    reps: [10, 20],
    sub: "lateral-raise",
    cues: "Lead with the elbows, stop around shoulder height. Ego here just recruits traps.",
  },
  {
    slug: "cable-lateral-raise",
    name: "Cable Lateral Raise",
    pattern: "isolation_upper",
    primary: ["side_delts"],
    equipment: ["cable_machine"],
    load: "cable_load",
    unilateral: true,
    complexity: 2,
    sfr: 5,
    reps: [10, 20],
    sub: "lateral-raise",
    cues: "Tension at the bottom where dumbbells give you none.",
  },
  {
    slug: "band-lateral-raise",
    name: "Band Lateral Raise",
    pattern: "isolation_upper",
    primary: ["side_delts"],
    equipment: ["mini_band"],
    load: "band",
    complexity: 1,
    sfr: 5,
    reps: [15, 30],
    sub: "lateral-raise",
  },
  {
    slug: "dumbbell-upright-row",
    name: "Upright Row",
    pattern: "isolation_upper",
    primary: ["side_delts", "traps"],
    secondary: ["biceps"],
    equipment: ["dumbbell"],
    load: "dumbbell_pair",
    complexity: 2,
    sfr: 4,
    reps: [10, 15],
    sub: "lateral-raise",
  },
  {
    slug: "dumbbell-reverse-fly",
    name: "Dumbbell Reverse Fly",
    aliases: ["rear delt fly"],
    pattern: "isolation_upper",
    primary: ["rear_delts"],
    secondary: ["upper_back"],
    equipment: ["dumbbell"],
    load: "dumbbell_pair",
    complexity: 1,
    sfr: 5,
    reps: [12, 20],
    sub: "rear-delt-upper-back",
  },
  {
    slug: "cable-reverse-fly",
    name: "Cable Reverse Fly",
    pattern: "isolation_upper",
    primary: ["rear_delts"],
    secondary: ["upper_back"],
    equipment: ["cable_machine"],
    load: "cable_load",
    complexity: 2,
    sfr: 5,
    reps: [12, 20],
    sub: "rear-delt-upper-back",
  },
  {
    slug: "band-reverse-fly",
    name: "Band Reverse Fly",
    pattern: "isolation_upper",
    primary: ["rear_delts"],
    secondary: ["upper_back"],
    equipment: ["resistance_band_long"],
    load: "band",
    complexity: 1,
    sfr: 5,
    reps: [15, 30],
    sub: "rear-delt-upper-back",
  },
  {
    slug: "barbell-shrug",
    name: "Barbell Shrug",
    pattern: "isolation_upper",
    primary: ["traps"],
    equipment: ["barbell", "weight_plate"],
    load: "barbell",
    complexity: 1,
    sfr: 5,
    reps: [8, 20],
    sub: "trap-shrug",
  },
  {
    slug: "dumbbell-shrug",
    name: "Dumbbell Shrug",
    pattern: "isolation_upper",
    primary: ["traps"],
    equipment: ["dumbbell"],
    load: "dumbbell_pair",
    complexity: 1,
    sfr: 5,
    reps: [10, 20],
    sub: "trap-shrug",
  },
];

export const LOWER_ISOLATION: ExerciseSeed[] = [
  {
    slug: "leg-extension",
    name: "Leg Extension",
    pattern: "isolation_lower",
    primary: ["quads"],
    equipment: ["leg_extension_machine"],
    load: "machine_load",
    complexity: 1,
    sfr: 5,
    reps: [10, 20],
    sub: "quad-isolation",
  },
  {
    slug: "sissy-squat",
    name: "Sissy Squat",
    pattern: "isolation_lower",
    primary: ["quads"],
    equipment: ["bodyweight"],
    optional: ["wall"],
    load: "bodyweight",
    complexity: 3,
    sfr: 4,
    reps: [8, 20],
    sub: "quad-isolation",
    cues: "Knees travel forward, hips stay extended. Rare thing: genuine quad isolation with no equipment.",
  },
  {
    slug: "standing-calf-raise",
    name: "Standing Calf Raise",
    pattern: "isolation_lower",
    primary: ["calves"],
    equipment: ["calf_raise_machine"],
    load: "machine_load",
    complexity: 1,
    sfr: 5,
    reps: [8, 20],
    sub: "calf-raise",
    cues: "Full stretch at the bottom, pause at the top. Calves respond to range, not bouncing.",
  },
  {
    slug: "seated-calf-raise",
    name: "Seated Calf Raise",
    pattern: "isolation_lower",
    primary: ["calves"],
    equipment: ["calf_raise_machine"],
    load: "machine_load",
    complexity: 1,
    sfr: 5,
    reps: [10, 25],
    sub: "calf-raise",
  },
  {
    slug: "dumbbell-calf-raise",
    name: "Dumbbell Calf Raise",
    pattern: "isolation_lower",
    primary: ["calves"],
    equipment: ["dumbbell"],
    load: "dumbbell_pair",
    complexity: 1,
    sfr: 5,
    reps: [12, 25],
    sub: "calf-raise",
  },
  {
    slug: "single-leg-calf-raise",
    name: "Single-Leg Calf Raise",
    pattern: "isolation_lower",
    primary: ["calves"],
    equipment: ["bodyweight"],
    optional: ["bench_or_chair", "dumbbell"],
    load: "bodyweight_loaded",
    unilateral: true,
    complexity: 1,
    sfr: 5,
    reps: [10, 25],
    sub: "calf-raise",
    cues: "Bodyweight on one leg is plenty of load for most people.",
  },
  {
    slug: "band-hip-abduction",
    name: "Band Hip Abduction",
    pattern: "isolation_lower",
    primary: ["abductors", "glutes"],
    equipment: ["mini_band"],
    load: "band",
    complexity: 1,
    sfr: 5,
    reps: [15, 30],
    sub: "hip-abduction",
  },
  {
    slug: "side-lying-hip-abduction",
    name: "Side-Lying Hip Abduction",
    pattern: "isolation_lower",
    primary: ["abductors", "glutes"],
    equipment: ["bodyweight"],
    optional: ["mini_band"],
    load: "bodyweight",
    unilateral: true,
    complexity: 1,
    sfr: 5,
    reps: [15, 30],
    sub: "hip-abduction",
  },
  {
    slug: "band-hip-adduction",
    name: "Band Hip Adduction",
    pattern: "isolation_lower",
    primary: ["adductors"],
    equipment: ["mini_band"],
    load: "band",
    unilateral: true,
    complexity: 1,
    sfr: 5,
    reps: [15, 30],
    sub: "adductor-isolation",
  },
  {
    slug: "copenhagen-plank",
    name: "Copenhagen Plank",
    pattern: "isolation_lower",
    primary: ["adductors"],
    secondary: ["obliques"],
    equipment: ["bodyweight", "bench_or_chair"],
    load: "time",
    unilateral: true,
    complexity: 3,
    sfr: 4,
    reps: [1, 1],
    sub: "adductor-isolation",
    cues: "One of very few ways to train the adductors hard with no equipment.",
  },
];

export const ISOLATION: ExerciseSeed[] = [...ARMS, ...DELTS_TRAPS, ...LOWER_ISOLATION];
