import type { ExerciseSeed } from "../types";

/**
 * Squat, hinge and lunge patterns.
 *
 * Coverage requirement: every one of these three patterns must have at least one
 * viable option in *each* equipment preset, including `bodyweight_only` and
 * `hotel_room`. `npm run seed:validate` enforces that — travel mode depends on
 * it, since a hotel session still owes the week its quota of squat and hinge work.
 */

export const SQUAT: ExerciseSeed[] = [
  {
    slug: "barbell-back-squat",
    name: "Barbell Back Squat",
    aliases: ["back squat", "squat"],
    pattern: "squat",
    primary: ["quads", "glutes"],
    secondary: ["hamstrings", "lower_back", "abs", "adductors"],
    equipment: ["barbell", "weight_plate", "squat_rack"],
    optional: ["power_rack", "weight_vest"],
    load: "barbell",
    compound: true,
    complexity: 4,
    sfr: 3,
    reps: [3, 8],
    sub: "squat-bilateral-loaded",
    setup: "Bar on upper traps (high bar) or across rear delts (low bar). Feet shoulder-width, toes slightly out.",
    cues: "Brace before you unrack. Sit between the hips, knees track over mid-foot, drive the floor apart on the way up.",
  },
  {
    slug: "barbell-front-squat",
    name: "Barbell Front Squat",
    aliases: ["front squat"],
    pattern: "squat",
    primary: ["quads"],
    secondary: ["glutes", "abs", "upper_back"],
    equipment: ["barbell", "weight_plate", "squat_rack"],
    load: "barbell",
    compound: true,
    complexity: 4,
    sfr: 3,
    reps: [3, 8],
    sub: "squat-bilateral-loaded",
    setup: "Bar in the front rack across the delts, elbows high.",
    cues: "Elbows up throughout — dropping them dumps the bar. Stay upright, sit straight down.",
  },
  {
    slug: "barbell-tempo-squat",
    name: "Barbell Tempo Squat",
    pattern: "squat",
    primary: ["quads", "glutes"],
    secondary: ["hamstrings", "abs"],
    equipment: ["barbell", "weight_plate", "squat_rack"],
    load: "barbell",
    compound: true,
    complexity: 4,
    sfr: 3,
    reps: [3, 6],
    sub: "squat-bilateral-loaded",
    cues: "Control the descent to the prescribed count. No bouncing out of the hole.",
  },
  {
    slug: "barbell-pause-squat",
    name: "Barbell Pause Squat",
    pattern: "squat",
    primary: ["quads", "glutes"],
    secondary: ["abs", "lower_back"],
    equipment: ["barbell", "weight_plate", "squat_rack"],
    load: "barbell",
    compound: true,
    complexity: 4,
    sfr: 3,
    reps: [3, 6],
    sub: "squat-bilateral-loaded",
    cues: "Hold the bottom without losing brace or letting the knees drift in.",
  },
  {
    slug: "barbell-box-squat",
    name: "Barbell Box Squat",
    pattern: "squat",
    primary: ["quads", "glutes"],
    secondary: ["hamstrings", "lower_back"],
    equipment: ["barbell", "weight_plate", "squat_rack", "box_plyo"],
    load: "barbell",
    compound: true,
    complexity: 4,
    sfr: 3,
    reps: [3, 8],
    sub: "squat-bilateral-loaded",
    cues: "Sit back to the box under control. Touch, don't collapse.",
  },
  {
    slug: "barbell-zercher-squat",
    name: "Zercher Squat",
    pattern: "squat",
    primary: ["quads", "glutes"],
    secondary: ["abs", "upper_back", "biceps"],
    equipment: ["barbell", "weight_plate"],
    optional: ["squat_rack"],
    load: "barbell",
    compound: true,
    complexity: 4,
    sfr: 3,
    reps: [5, 10],
    sub: "squat-bilateral-loaded",
    setup: "Bar cradled in the elbow crooks.",
    cues: "Brutal on the mid-section. Keep the chest tall and elbows tight to the body.",
  },
  {
    slug: "safety-bar-squat",
    name: "Safety Bar Squat",
    aliases: ["SSB squat"],
    pattern: "squat",
    primary: ["quads", "glutes"],
    secondary: ["hamstrings", "upper_back"],
    equipment: ["barbell", "weight_plate", "squat_rack"],
    load: "barbell",
    compound: true,
    complexity: 3,
    sfr: 4,
    reps: [5, 10],
    sub: "squat-bilateral-loaded",
    cues: "The bar wants to tip you forward — fight it with the upper back.",
  },
  {
    slug: "smith-machine-squat",
    name: "Smith Machine Squat",
    pattern: "squat",
    primary: ["quads", "glutes"],
    secondary: ["hamstrings"],
    equipment: ["smith_machine"],
    load: "machine_load",
    compound: true,
    complexity: 2,
    sfr: 4,
    reps: [6, 12],
    sub: "squat-machine",
  },
  {
    slug: "hack-squat",
    name: "Hack Squat",
    pattern: "squat",
    primary: ["quads"],
    secondary: ["glutes"],
    equipment: ["hack_squat"],
    load: "machine_load",
    compound: true,
    complexity: 2,
    sfr: 5,
    reps: [6, 15],
    sub: "squat-machine",
    cues: "Excellent quad stimulus for very little systemic cost. Push through the whole foot.",
  },
  {
    slug: "leg-press",
    name: "Leg Press",
    pattern: "squat",
    primary: ["quads", "glutes"],
    secondary: ["hamstrings"],
    equipment: ["leg_press"],
    load: "machine_load",
    compound: true,
    complexity: 1,
    sfr: 5,
    reps: [8, 20],
    sub: "squat-machine",
    cues: "Don't let the lower back round off the pad at the bottom.",
  },
  {
    slug: "landmine-squat",
    name: "Landmine Squat",
    pattern: "squat",
    primary: ["quads", "glutes"],
    secondary: ["abs", "upper_back"],
    equipment: ["landmine", "barbell", "weight_plate"],
    load: "barbell",
    compound: true,
    complexity: 2,
    sfr: 4,
    reps: [8, 15],
    sub: "squat-bilateral-loaded",
  },
  {
    slug: "goblet-squat",
    name: "Goblet Squat",
    pattern: "squat",
    primary: ["quads", "glutes"],
    secondary: ["abs", "upper_back"],
    equipment: ["kettlebell"],
    load: "kettlebell",
    compound: true,
    complexity: 1,
    sfr: 4,
    reps: [8, 15],
    sub: "squat-loaded-portable",
    cues: "Hold the bell tight to the chest. Elbows inside the knees at the bottom.",
  },
  {
    slug: "dumbbell-goblet-squat",
    name: "Dumbbell Goblet Squat",
    pattern: "squat",
    primary: ["quads", "glutes"],
    secondary: ["abs"],
    equipment: ["dumbbell"],
    load: "dumbbell_single",
    compound: true,
    complexity: 1,
    sfr: 4,
    reps: [8, 15],
    sub: "squat-loaded-portable",
  },
  {
    slug: "dumbbell-front-squat",
    name: "Dumbbell Front Squat",
    pattern: "squat",
    primary: ["quads", "glutes"],
    secondary: ["abs", "front_delts"],
    equipment: ["dumbbell"],
    load: "dumbbell_pair",
    compound: true,
    complexity: 2,
    sfr: 4,
    reps: [6, 12],
    sub: "squat-loaded-portable",
    setup: "Dumbbells racked on the shoulders.",
  },
  {
    slug: "heels-elevated-goblet-squat",
    name: "Heels-Elevated Goblet Squat",
    pattern: "squat",
    primary: ["quads"],
    secondary: ["glutes"],
    equipment: ["dumbbell", "weight_plate"],
    load: "dumbbell_single",
    compound: true,
    complexity: 1,
    sfr: 4,
    reps: [10, 15],
    sub: "squat-loaded-portable",
    cues: "Elevating the heels biases the quads and lets you sit more upright.",
  },
  {
    slug: "band-squat",
    name: "Banded Squat",
    pattern: "squat",
    primary: ["quads", "glutes"],
    secondary: ["abs"],
    equipment: ["resistance_band_long"],
    load: "band",
    compound: true,
    complexity: 1,
    sfr: 3,
    reps: [12, 25],
    sub: "squat-bodyweight",
    setup: "Stand on the band, loop it over the shoulders.",
    cues: "Tension rises as you stand — accelerate through the top.",
  },
  {
    slug: "bodyweight-squat",
    name: "Bodyweight Squat",
    aliases: ["air squat"],
    pattern: "squat",
    primary: ["quads", "glutes"],
    equipment: ["bodyweight"],
    load: "bodyweight",
    compound: true,
    complexity: 1,
    sfr: 4,
    reps: [15, 40],
    sub: "squat-bodyweight",
  },
  {
    slug: "tempo-bodyweight-squat",
    name: "Tempo Bodyweight Squat",
    pattern: "squat",
    primary: ["quads", "glutes"],
    equipment: ["bodyweight"],
    load: "bodyweight",
    compound: true,
    complexity: 1,
    sfr: 4,
    reps: [10, 20],
    sub: "squat-bodyweight",
    cues: "Slow descent and a pause make bodyweight work genuinely hard when load is unavailable.",
  },
  {
    slug: "squat-jump",
    name: "Squat Jump",
    pattern: "squat",
    primary: ["quads", "glutes"],
    secondary: ["calves"],
    equipment: ["bodyweight"],
    load: "bodyweight",
    compound: true,
    complexity: 2,
    sfr: 3,
    reps: [5, 15],
    sub: "squat-bodyweight",
    cues: "Land soft, absorb through the hips. Quality over quantity.",
  },
  {
    slug: "pistol-squat",
    name: "Pistol Squat",
    aliases: ["single leg squat"],
    pattern: "squat",
    primary: ["quads", "glutes"],
    secondary: ["hamstrings", "abs"],
    equipment: ["bodyweight"],
    optional: ["bench_or_chair"],
    load: "bodyweight",
    unilateral: true,
    compound: true,
    complexity: 5,
    sfr: 3,
    reps: [3, 10],
    sub: "squat-bodyweight-unilateral",
    cues: "Genuine strength work with no equipment. Hold a doorframe if balance is the limiter, not strength.",
  },
  {
    slug: "assisted-pistol-squat",
    name: "Assisted Pistol Squat",
    aliases: ["box pistol squat"],
    pattern: "squat",
    primary: ["quads", "glutes"],
    secondary: ["hamstrings", "abs"],
    equipment: ["bodyweight", "bench_or_chair"],
    load: "bodyweight",
    unilateral: true,
    compound: true,
    complexity: 3,
    sfr: 4,
    reps: [5, 12],
    sub: "squat-bodyweight-unilateral",
    cues: "Sit to a chair or hold a support. The stepping stone to a full pistol.",
  },
  {
    slug: "wall-sit",
    name: "Wall Sit",
    pattern: "squat",
    primary: ["quads"],
    secondary: ["glutes"],
    equipment: ["bodyweight", "wall"],
    load: "time",
    complexity: 1,
    sfr: 4,
    reps: [1, 1],
    sub: "squat-bodyweight",
    cues: "Thighs parallel to the floor. Isometric, so progress it in seconds.",
  },
];

export const HINGE: ExerciseSeed[] = [
  {
    slug: "conventional-deadlift",
    name: "Conventional Deadlift",
    aliases: ["deadlift"],
    pattern: "hinge",
    primary: ["glutes", "hamstrings", "lower_back"],
    secondary: ["quads", "upper_back", "traps", "forearms"],
    equipment: ["barbell", "weight_plate"],
    optional: ["dip_belt"],
    load: "barbell",
    compound: true,
    complexity: 4,
    // Deliberately low: superb lift, but the systemic fatigue cost is the
    // highest in the library, so the selector should not spam it.
    sfr: 2,
    reps: [1, 6],
    sub: "hinge-bilateral-heavy",
    setup: "Bar over mid-foot, shins close, shoulders slightly ahead of the bar.",
    cues: "Take the slack out before you pull. Push the floor away, keep the bar against the legs.",
  },
  {
    slug: "sumo-deadlift",
    name: "Sumo Deadlift",
    pattern: "hinge",
    primary: ["glutes", "quads"],
    secondary: ["hamstrings", "adductors", "upper_back", "traps"],
    equipment: ["barbell", "weight_plate"],
    load: "barbell",
    compound: true,
    complexity: 4,
    sfr: 2,
    reps: [1, 6],
    sub: "hinge-bilateral-heavy",
    cues: "Open the hips, knees out over the toes, chest up before the bar moves.",
  },
  {
    slug: "trap-bar-deadlift",
    name: "Trap Bar Deadlift",
    aliases: ["hex bar deadlift"],
    pattern: "hinge",
    primary: ["glutes", "quads", "hamstrings"],
    secondary: ["upper_back", "traps", "forearms"],
    equipment: ["trap_bar", "weight_plate"],
    load: "barbell",
    compound: true,
    complexity: 2,
    sfr: 3,
    reps: [3, 10],
    sub: "hinge-bilateral-heavy",
    cues: "More forgiving on the lower back than a straight bar, and easier to load safely.",
  },
  {
    slug: "romanian-deadlift",
    name: "Romanian Deadlift",
    aliases: ["RDL"],
    pattern: "hinge",
    primary: ["hamstrings", "glutes"],
    secondary: ["lower_back", "upper_back"],
    equipment: ["barbell", "weight_plate"],
    load: "barbell",
    compound: true,
    complexity: 3,
    sfr: 4,
    reps: [6, 12],
    sub: "hinge-bilateral-moderate",
    cues: "Push the hips back, keep a soft knee. Stop when the hamstrings run out of length, not when the bar hits the floor.",
  },
  {
    slug: "stiff-leg-deadlift",
    name: "Stiff-Leg Deadlift",
    pattern: "hinge",
    primary: ["hamstrings", "glutes"],
    secondary: ["lower_back"],
    equipment: ["barbell", "weight_plate"],
    load: "barbell",
    compound: true,
    complexity: 3,
    sfr: 3,
    reps: [6, 12],
    sub: "hinge-bilateral-moderate",
  },
  {
    slug: "deficit-deadlift",
    name: "Deficit Deadlift",
    pattern: "hinge",
    primary: ["glutes", "hamstrings", "lower_back"],
    secondary: ["quads", "upper_back"],
    equipment: ["barbell", "weight_plate", "box_plyo"],
    load: "barbell",
    compound: true,
    complexity: 4,
    sfr: 2,
    reps: [3, 6],
    sub: "hinge-bilateral-heavy",
  },
  {
    slug: "rack-pull",
    name: "Rack Pull",
    pattern: "hinge",
    primary: ["glutes", "lower_back"],
    secondary: ["hamstrings", "traps", "upper_back", "forearms"],
    equipment: ["barbell", "weight_plate", "power_rack"],
    load: "barbell",
    compound: true,
    complexity: 3,
    sfr: 3,
    reps: [3, 8],
    sub: "hinge-bilateral-heavy",
  },
  {
    slug: "barbell-good-morning",
    name: "Barbell Good Morning",
    pattern: "hinge",
    primary: ["hamstrings", "glutes"],
    secondary: ["lower_back", "upper_back"],
    equipment: ["barbell", "weight_plate", "squat_rack"],
    load: "barbell",
    compound: true,
    complexity: 4,
    sfr: 3,
    reps: [6, 12],
    sub: "hinge-bilateral-moderate",
    cues: "Light loads only. Hips back, spine neutral throughout.",
  },
  {
    slug: "barbell-hip-thrust",
    name: "Barbell Hip Thrust",
    pattern: "hinge",
    primary: ["glutes"],
    secondary: ["hamstrings"],
    equipment: ["barbell", "weight_plate", "bench_flat"],
    load: "barbell",
    compound: true,
    complexity: 2,
    sfr: 5,
    reps: [8, 15],
    sub: "hinge-glute-dominant",
    cues: "Ribs down, chin tucked. Full lockout, squeeze rather than hyperextend the lower back.",
  },
  {
    slug: "dumbbell-romanian-deadlift",
    name: "Dumbbell Romanian Deadlift",
    aliases: ["DB RDL"],
    pattern: "hinge",
    primary: ["hamstrings", "glutes"],
    secondary: ["lower_back"],
    equipment: ["dumbbell"],
    load: "dumbbell_pair",
    compound: true,
    complexity: 2,
    sfr: 4,
    reps: [8, 15],
    sub: "hinge-portable",
  },
  {
    slug: "single-leg-dumbbell-rdl",
    name: "Single-Leg Dumbbell RDL",
    pattern: "hinge",
    primary: ["hamstrings", "glutes"],
    secondary: ["lower_back", "abs"],
    equipment: ["dumbbell"],
    load: "dumbbell_single",
    unilateral: true,
    compound: true,
    complexity: 3,
    sfr: 4,
    reps: [8, 12],
    sub: "hinge-portable-unilateral",
    cues: "Hips square — resist the urge to open the trailing hip.",
  },
  {
    slug: "kettlebell-swing",
    name: "Kettlebell Swing",
    pattern: "hinge",
    primary: ["glutes", "hamstrings"],
    secondary: ["lower_back", "abs", "side_delts"],
    equipment: ["kettlebell"],
    load: "kettlebell",
    compound: true,
    complexity: 3,
    sfr: 4,
    reps: [10, 25],
    sub: "hinge-portable",
    cues: "A hinge, not a squat, and not a shoulder raise. The hips throw the bell.",
  },
  {
    slug: "kettlebell-deadlift",
    name: "Kettlebell Deadlift",
    pattern: "hinge",
    primary: ["glutes", "hamstrings"],
    secondary: ["lower_back", "forearms"],
    equipment: ["kettlebell"],
    load: "kettlebell",
    compound: true,
    complexity: 1,
    sfr: 4,
    reps: [8, 15],
    sub: "hinge-portable",
  },
  {
    slug: "cable-pull-through",
    name: "Cable Pull-Through",
    pattern: "hinge",
    primary: ["glutes", "hamstrings"],
    secondary: ["lower_back"],
    equipment: ["cable_machine"],
    load: "cable_load",
    complexity: 2,
    sfr: 5,
    reps: [10, 20],
    sub: "hinge-glute-dominant",
  },
  {
    slug: "band-pull-through",
    name: "Band Pull-Through",
    pattern: "hinge",
    primary: ["glutes", "hamstrings"],
    equipment: ["resistance_band_long"],
    load: "band",
    complexity: 1,
    sfr: 4,
    reps: [12, 25],
    sub: "hinge-glute-dominant",
    setup: "Anchor the band low behind you, straddle it and hold between the legs.",
  },
  {
    slug: "band-romanian-deadlift",
    name: "Band Romanian Deadlift",
    pattern: "hinge",
    primary: ["hamstrings", "glutes"],
    equipment: ["resistance_band_long"],
    load: "band",
    complexity: 1,
    sfr: 3,
    reps: [12, 25],
    sub: "hinge-portable",
    setup: "Stand on the band, hold the ends at hip height.",
  },
  {
    slug: "lying-leg-curl",
    name: "Lying Leg Curl",
    pattern: "hinge",
    primary: ["hamstrings"],
    secondary: ["calves"],
    equipment: ["leg_curl_machine"],
    load: "machine_load",
    complexity: 1,
    sfr: 5,
    reps: [8, 15],
    sub: "hamstring-isolation",
    cues: "Knee flexion, which the RDL family barely trains. Worth including for both function and hypertrophy.",
  },
  {
    slug: "seated-leg-curl",
    name: "Seated Leg Curl",
    pattern: "hinge",
    primary: ["hamstrings"],
    equipment: ["leg_curl_machine"],
    load: "machine_load",
    complexity: 1,
    sfr: 5,
    reps: [8, 15],
    sub: "hamstring-isolation",
    cues: "Trains the hamstrings in a lengthened position — strong hypertrophy stimulus.",
  },
  {
    slug: "nordic-hamstring-curl",
    name: "Nordic Hamstring Curl",
    pattern: "hinge",
    primary: ["hamstrings"],
    secondary: ["glutes", "calves"],
    equipment: ["bodyweight"],
    optional: ["glute_ham_raise", "bench_or_chair"],
    load: "bodyweight",
    complexity: 4,
    sfr: 3,
    reps: [3, 8],
    sub: "hamstring-isolation",
    setup: "Anchor the heels under something immovable, kneel on something padded.",
    cues: "Lower as slowly as you can control, then push off the floor to reset. Brutally effective with no load.",
  },
  {
    slug: "glute-bridge",
    name: "Glute Bridge",
    pattern: "hinge",
    primary: ["glutes"],
    secondary: ["hamstrings"],
    equipment: ["bodyweight"],
    load: "bodyweight",
    complexity: 1,
    sfr: 4,
    reps: [15, 30],
    sub: "hinge-glute-dominant",
  },
  {
    slug: "single-leg-glute-bridge",
    name: "Single-Leg Glute Bridge",
    pattern: "hinge",
    primary: ["glutes"],
    secondary: ["hamstrings"],
    equipment: ["bodyweight"],
    load: "bodyweight",
    unilateral: true,
    complexity: 2,
    sfr: 4,
    reps: [10, 20],
    sub: "hinge-glute-dominant",
  },
  {
    slug: "single-leg-hip-thrust-bench",
    name: "Single-Leg Hip Thrust",
    pattern: "hinge",
    primary: ["glutes"],
    secondary: ["hamstrings"],
    equipment: ["bodyweight", "bench_or_chair"],
    load: "bodyweight",
    unilateral: true,
    complexity: 2,
    sfr: 4,
    reps: [8, 20],
    sub: "hinge-glute-dominant",
  },
  {
    slug: "single-leg-bodyweight-rdl",
    name: "Single-Leg Bodyweight RDL",
    pattern: "hinge",
    primary: ["hamstrings", "glutes"],
    secondary: ["lower_back", "abs"],
    equipment: ["bodyweight"],
    load: "bodyweight",
    unilateral: true,
    complexity: 2,
    sfr: 4,
    reps: [10, 20],
    sub: "hinge-portable-unilateral",
    cues: "Slow and controlled, reaching for the floor. Balance demand does a lot of the work.",
  },
  {
    slug: "bodyweight-good-morning",
    name: "Bodyweight Good Morning",
    pattern: "hinge",
    primary: ["hamstrings", "glutes"],
    secondary: ["lower_back"],
    equipment: ["bodyweight"],
    load: "bodyweight",
    complexity: 1,
    sfr: 3,
    reps: [15, 30],
    sub: "hinge-portable",
  },
  {
    slug: "back-extension",
    name: "Back Extension",
    aliases: ["hyperextension", "45 degree back extension"],
    pattern: "hinge",
    primary: ["lower_back", "glutes"],
    secondary: ["hamstrings"],
    equipment: ["back_extension_bench"],
    load: "bodyweight_loaded",
    complexity: 1,
    sfr: 4,
    reps: [10, 20],
    sub: "hinge-glute-dominant",
  },
];

export const LUNGE: ExerciseSeed[] = [
  {
    slug: "bulgarian-split-squat",
    name: "Bulgarian Split Squat",
    aliases: ["BSS", "rear foot elevated split squat", "RFESS"],
    pattern: "lunge",
    primary: ["quads", "glutes"],
    secondary: ["hamstrings", "adductors"],
    equipment: ["bodyweight", "bench_or_chair"],
    optional: ["dumbbell", "kettlebell", "barbell"],
    load: "bodyweight_loaded",
    unilateral: true,
    compound: true,
    complexity: 3,
    sfr: 4,
    reps: [6, 15],
    sub: "lunge-unilateral",
    cues: "Front shin roughly vertical for quads, torso leaned forward for glutes. Loadable with anything, or nothing.",
  },
  {
    slug: "dumbbell-split-squat",
    name: "Dumbbell Split Squat",
    pattern: "lunge",
    primary: ["quads", "glutes"],
    secondary: ["hamstrings"],
    equipment: ["dumbbell"],
    load: "dumbbell_pair",
    unilateral: true,
    compound: true,
    complexity: 2,
    sfr: 4,
    reps: [8, 15],
    sub: "lunge-unilateral",
  },
  {
    slug: "dumbbell-walking-lunge",
    name: "Dumbbell Walking Lunge",
    pattern: "lunge",
    primary: ["quads", "glutes"],
    secondary: ["hamstrings", "adductors", "abs"],
    equipment: ["dumbbell"],
    load: "dumbbell_pair",
    unilateral: true,
    compound: true,
    complexity: 2,
    sfr: 3,
    reps: [8, 20],
    sub: "lunge-unilateral",
  },
  {
    slug: "dumbbell-reverse-lunge",
    name: "Dumbbell Reverse Lunge",
    pattern: "lunge",
    primary: ["quads", "glutes"],
    secondary: ["hamstrings"],
    equipment: ["dumbbell"],
    load: "dumbbell_pair",
    unilateral: true,
    compound: true,
    complexity: 2,
    sfr: 4,
    reps: [8, 15],
    sub: "lunge-unilateral",
    cues: "Kinder to the knees than a forward lunge, and easier to load heavy.",
  },
  {
    slug: "barbell-lunge",
    name: "Barbell Lunge",
    pattern: "lunge",
    primary: ["quads", "glutes"],
    secondary: ["hamstrings", "abs"],
    equipment: ["barbell", "weight_plate", "squat_rack"],
    load: "barbell",
    unilateral: true,
    compound: true,
    complexity: 3,
    sfr: 3,
    reps: [6, 12],
    sub: "lunge-unilateral",
  },
  {
    slug: "dumbbell-step-up",
    name: "Dumbbell Step-Up",
    pattern: "lunge",
    primary: ["quads", "glutes"],
    secondary: ["hamstrings", "calves"],
    equipment: ["dumbbell", "box_plyo"],
    load: "dumbbell_pair",
    unilateral: true,
    compound: true,
    complexity: 2,
    sfr: 4,
    reps: [8, 15],
    sub: "lunge-unilateral",
    cues: "Drive through the top leg — don't push off the trailing foot.",
  },
  {
    slug: "bodyweight-step-up",
    name: "Step-Up",
    pattern: "lunge",
    primary: ["quads", "glutes"],
    secondary: ["calves"],
    equipment: ["bodyweight", "bench_or_chair"],
    load: "bodyweight",
    unilateral: true,
    compound: true,
    complexity: 1,
    sfr: 4,
    reps: [10, 20],
    sub: "lunge-bodyweight",
  },
  {
    slug: "bodyweight-reverse-lunge",
    name: "Bodyweight Reverse Lunge",
    pattern: "lunge",
    primary: ["quads", "glutes"],
    secondary: ["hamstrings"],
    equipment: ["bodyweight"],
    load: "bodyweight",
    unilateral: true,
    compound: true,
    complexity: 1,
    sfr: 4,
    reps: [10, 25],
    sub: "lunge-bodyweight",
  },
  {
    slug: "bodyweight-split-squat",
    name: "Bodyweight Split Squat",
    pattern: "lunge",
    primary: ["quads", "glutes"],
    equipment: ["bodyweight"],
    load: "bodyweight",
    unilateral: true,
    compound: true,
    complexity: 1,
    sfr: 4,
    reps: [10, 25],
    sub: "lunge-bodyweight",
  },
  {
    slug: "lateral-lunge",
    name: "Lateral Lunge",
    pattern: "lunge",
    primary: ["quads", "glutes", "adductors"],
    secondary: ["hamstrings"],
    equipment: ["bodyweight"],
    optional: ["dumbbell", "kettlebell"],
    load: "bodyweight_loaded",
    unilateral: true,
    compound: true,
    complexity: 2,
    sfr: 4,
    reps: [8, 15],
    sub: "lunge-bodyweight",
    cues: "One of the few movements that trains the adductors through range.",
  },
  {
    slug: "jumping-lunge",
    name: "Jumping Lunge",
    pattern: "lunge",
    primary: ["quads", "glutes"],
    secondary: ["calves", "hamstrings"],
    equipment: ["bodyweight"],
    load: "bodyweight",
    unilateral: true,
    complexity: 3,
    sfr: 2,
    reps: [8, 20],
    sub: "lunge-bodyweight",
  },
  {
    slug: "band-split-squat",
    name: "Band Split Squat",
    pattern: "lunge",
    primary: ["quads", "glutes"],
    equipment: ["resistance_band_long"],
    load: "band",
    unilateral: true,
    compound: true,
    complexity: 2,
    sfr: 4,
    reps: [10, 20],
    sub: "lunge-unilateral",
  },
];

export const LOWER_BODY: ExerciseSeed[] = [...SQUAT, ...HINGE, ...LUNGE];
