import type { ExerciseSeed } from "../types";

/**
 * Horizontal and vertical pushing.
 *
 * Dips are classified as `horizontal_push` despite the body travelling
 * vertically. The classification exists to drive substitution and session
 * balance, and a dip substitutes for chest pressing far more usefully than it
 * substitutes for an overhead press.
 */

export const HORIZONTAL_PUSH: ExerciseSeed[] = [
  {
    slug: "barbell-bench-press",
    name: "Barbell Bench Press",
    aliases: ["bench press", "flat bench"],
    pattern: "horizontal_push",
    primary: ["chest"],
    secondary: ["triceps", "front_delts"],
    equipment: ["barbell", "weight_plate", "bench_flat"],
    optional: ["power_rack"],
    load: "barbell",
    compound: true,
    complexity: 3,
    sfr: 3,
    reps: [3, 10],
    sub: "horizontal-push-barbell",
    setup: "Shoulder blades retracted and down, feet planted, slight arch.",
    cues: "Bar to the lower chest, elbows tucked around 45 degrees. Drive the bench away from you.",
  },
  {
    slug: "barbell-incline-bench-press",
    name: "Barbell Incline Bench Press",
    aliases: ["incline bench"],
    pattern: "horizontal_push",
    primary: ["chest", "front_delts"],
    secondary: ["triceps"],
    equipment: ["barbell", "weight_plate", "bench_adjustable"],
    optional: ["power_rack"],
    load: "barbell",
    compound: true,
    complexity: 3,
    sfr: 4,
    reps: [5, 12],
    sub: "horizontal-push-barbell",
    cues: "30-45 degrees. Biases the upper chest, which flat pressing under-trains.",
  },
  {
    slug: "barbell-close-grip-bench-press",
    name: "Close-Grip Bench Press",
    pattern: "horizontal_push",
    primary: ["triceps", "chest"],
    secondary: ["front_delts"],
    equipment: ["barbell", "weight_plate", "bench_flat"],
    load: "barbell",
    compound: true,
    complexity: 3,
    sfr: 4,
    reps: [5, 12],
    sub: "horizontal-push-barbell",
  },
  {
    slug: "barbell-floor-press",
    name: "Barbell Floor Press",
    pattern: "horizontal_push",
    primary: ["chest", "triceps"],
    secondary: ["front_delts"],
    equipment: ["barbell", "weight_plate"],
    load: "barbell",
    compound: true,
    complexity: 3,
    sfr: 4,
    reps: [5, 10],
    sub: "horizontal-push-barbell",
    cues: "No bench needed. The floor caps the range, which is easier on the shoulders.",
  },
  {
    slug: "barbell-paused-bench-press",
    name: "Paused Bench Press",
    pattern: "horizontal_push",
    primary: ["chest"],
    secondary: ["triceps", "front_delts"],
    equipment: ["barbell", "weight_plate", "bench_flat"],
    load: "barbell",
    compound: true,
    complexity: 3,
    sfr: 3,
    reps: [3, 8],
    sub: "horizontal-push-barbell",
  },
  {
    slug: "dumbbell-bench-press",
    name: "Dumbbell Bench Press",
    pattern: "horizontal_push",
    primary: ["chest"],
    secondary: ["triceps", "front_delts"],
    equipment: ["dumbbell", "bench_flat"],
    load: "dumbbell_pair",
    compound: true,
    complexity: 2,
    sfr: 4,
    reps: [6, 15],
    sub: "horizontal-push-dumbbell",
    cues: "Greater range than a barbell and each side works independently.",
  },
  {
    slug: "dumbbell-incline-press",
    name: "Dumbbell Incline Press",
    pattern: "horizontal_push",
    primary: ["chest", "front_delts"],
    secondary: ["triceps"],
    equipment: ["dumbbell", "bench_adjustable"],
    load: "dumbbell_pair",
    compound: true,
    complexity: 2,
    sfr: 4,
    reps: [6, 15],
    sub: "horizontal-push-dumbbell",
  },
  {
    slug: "dumbbell-floor-press",
    name: "Dumbbell Floor Press",
    pattern: "horizontal_push",
    primary: ["chest", "triceps"],
    equipment: ["dumbbell"],
    load: "dumbbell_pair",
    compound: true,
    complexity: 1,
    sfr: 4,
    reps: [8, 15],
    sub: "horizontal-push-dumbbell",
    cues: "The travel-friendly press: dumbbells and a floor, no bench required.",
  },
  {
    slug: "machine-chest-press",
    name: "Machine Chest Press",
    pattern: "horizontal_push",
    primary: ["chest"],
    secondary: ["triceps", "front_delts"],
    equipment: ["chest_press_machine"],
    load: "machine_load",
    compound: true,
    complexity: 1,
    sfr: 5,
    reps: [8, 15],
    sub: "horizontal-push-machine",
  },
  {
    slug: "cable-chest-press",
    name: "Cable Chest Press",
    pattern: "horizontal_push",
    primary: ["chest"],
    secondary: ["triceps", "front_delts"],
    equipment: ["cable_machine"],
    load: "cable_load",
    compound: true,
    complexity: 2,
    sfr: 5,
    reps: [8, 15],
    sub: "horizontal-push-machine",
  },
  {
    slug: "pec-deck-fly",
    name: "Pec Deck Fly",
    aliases: ["machine fly"],
    pattern: "isolation_upper",
    primary: ["chest"],
    equipment: ["pec_deck"],
    load: "machine_load",
    complexity: 1,
    sfr: 5,
    reps: [10, 20],
    sub: "chest-isolation",
  },
  {
    slug: "cable-fly",
    name: "Cable Fly",
    pattern: "isolation_upper",
    primary: ["chest"],
    equipment: ["cable_machine"],
    load: "cable_load",
    complexity: 2,
    sfr: 5,
    reps: [10, 20],
    sub: "chest-isolation",
    cues: "Constant tension through the whole range, unlike a dumbbell fly.",
  },
  {
    slug: "dumbbell-fly",
    name: "Dumbbell Fly",
    pattern: "isolation_upper",
    primary: ["chest"],
    equipment: ["dumbbell", "bench_flat"],
    load: "dumbbell_pair",
    complexity: 2,
    sfr: 4,
    reps: [10, 20],
    sub: "chest-isolation",
  },
  {
    slug: "chest-dip",
    name: "Chest Dip",
    aliases: ["dip", "dips"],
    pattern: "horizontal_push",
    primary: ["chest", "triceps"],
    secondary: ["front_delts"],
    equipment: ["dip_bars"],
    optional: ["dip_belt", "weight_vest"],
    load: "bodyweight_loaded",
    compound: true,
    complexity: 3,
    sfr: 4,
    reps: [5, 15],
    sub: "horizontal-push-bodyweight",
    cues: "Lean forward to bias the chest, stay upright for triceps. Loadable with a belt.",
  },
  {
    slug: "ring-dip",
    name: "Ring Dip",
    pattern: "horizontal_push",
    primary: ["chest", "triceps"],
    secondary: ["front_delts"],
    equipment: ["gymnastic_rings"],
    load: "bodyweight_loaded",
    compound: true,
    complexity: 5,
    sfr: 3,
    reps: [3, 12],
    sub: "horizontal-push-bodyweight",
  },
  {
    slug: "push-up",
    name: "Push-Up",
    pattern: "horizontal_push",
    primary: ["chest"],
    secondary: ["triceps", "front_delts", "abs"],
    equipment: ["bodyweight"],
    optional: ["weight_vest"],
    load: "bodyweight_loaded",
    compound: true,
    complexity: 1,
    sfr: 4,
    reps: [8, 30],
    sub: "horizontal-push-bodyweight",
    cues: "A moving plank. Ribs down, glutes on, body in one line.",
  },
  {
    slug: "deficit-push-up",
    name: "Deficit Push-Up",
    pattern: "horizontal_push",
    primary: ["chest"],
    secondary: ["triceps", "front_delts"],
    equipment: ["bodyweight", "dumbbell"],
    load: "bodyweight",
    compound: true,
    complexity: 2,
    sfr: 4,
    reps: [6, 20],
    sub: "horizontal-push-bodyweight",
    setup: "Hands elevated on dumbbells or books to let the chest drop below the hands.",
  },
  {
    slug: "decline-push-up",
    name: "Decline Push-Up",
    aliases: ["feet elevated push up"],
    pattern: "horizontal_push",
    primary: ["chest", "front_delts"],
    secondary: ["triceps"],
    equipment: ["bodyweight", "bench_or_chair"],
    load: "bodyweight",
    compound: true,
    complexity: 2,
    sfr: 4,
    reps: [8, 25],
    sub: "horizontal-push-bodyweight",
    cues: "Elevating the feet shifts load onto the upper chest and shoulders.",
  },
  {
    slug: "incline-push-up",
    name: "Incline Push-Up",
    pattern: "horizontal_push",
    primary: ["chest"],
    secondary: ["triceps"],
    equipment: ["bodyweight", "bench_or_chair"],
    load: "bodyweight",
    compound: true,
    complexity: 1,
    sfr: 4,
    reps: [10, 30],
    sub: "horizontal-push-bodyweight",
  },
  {
    slug: "diamond-push-up",
    name: "Diamond Push-Up",
    pattern: "horizontal_push",
    primary: ["triceps", "chest"],
    equipment: ["bodyweight"],
    load: "bodyweight",
    compound: true,
    complexity: 2,
    sfr: 4,
    reps: [6, 20],
    sub: "horizontal-push-bodyweight",
  },
  {
    slug: "archer-push-up",
    name: "Archer Push-Up",
    pattern: "horizontal_push",
    primary: ["chest", "triceps"],
    secondary: ["abs"],
    equipment: ["bodyweight"],
    load: "bodyweight",
    unilateral: true,
    compound: true,
    complexity: 4,
    sfr: 3,
    reps: [4, 12],
    sub: "horizontal-push-bodyweight",
    cues: "A genuine strength progression when you have no load available.",
  },
  {
    slug: "band-chest-press",
    name: "Band Chest Press",
    pattern: "horizontal_push",
    primary: ["chest"],
    secondary: ["triceps", "front_delts"],
    equipment: ["resistance_band_long"],
    load: "band",
    compound: true,
    complexity: 1,
    sfr: 4,
    reps: [10, 25],
    sub: "horizontal-push-bodyweight",
    setup: "Band around the back, under the arms, ends in each hand.",
  },
  {
    slug: "band-fly",
    name: "Band Fly",
    pattern: "isolation_upper",
    primary: ["chest"],
    equipment: ["resistance_band_long"],
    load: "band",
    complexity: 1,
    sfr: 4,
    reps: [12, 25],
    sub: "chest-isolation",
  },
  {
    slug: "suspension-trainer-push-up",
    name: "Suspension Trainer Push-Up",
    pattern: "horizontal_push",
    primary: ["chest"],
    secondary: ["triceps", "abs", "front_delts"],
    equipment: ["suspension_trainer"],
    load: "bodyweight",
    compound: true,
    complexity: 3,
    sfr: 4,
    reps: [6, 20],
    sub: "horizontal-push-bodyweight",
  },
];

export const VERTICAL_PUSH: ExerciseSeed[] = [
  {
    slug: "barbell-overhead-press",
    name: "Barbell Overhead Press",
    aliases: ["OHP", "military press", "strict press"],
    pattern: "vertical_push",
    primary: ["front_delts"],
    secondary: ["triceps", "side_delts", "abs", "upper_back"],
    equipment: ["barbell", "weight_plate"],
    optional: ["squat_rack"],
    load: "barbell",
    compound: true,
    complexity: 3,
    sfr: 3,
    reps: [3, 10],
    sub: "vertical-push-barbell",
    cues: "Brace hard, squeeze the glutes. Head back out of the way, then finish with the bar over the ears.",
  },
  {
    slug: "barbell-push-press",
    name: "Barbell Push Press",
    pattern: "vertical_push",
    primary: ["front_delts"],
    secondary: ["triceps", "quads", "abs"],
    equipment: ["barbell", "weight_plate"],
    optional: ["squat_rack"],
    load: "barbell",
    compound: true,
    complexity: 4,
    sfr: 3,
    reps: [3, 8],
    sub: "vertical-push-barbell",
    cues: "Short dip, aggressive leg drive, then punch through with the arms.",
  },
  {
    slug: "seated-barbell-press",
    name: "Seated Barbell Press",
    pattern: "vertical_push",
    primary: ["front_delts"],
    secondary: ["triceps", "side_delts"],
    equipment: ["barbell", "weight_plate", "bench_adjustable", "squat_rack"],
    load: "barbell",
    compound: true,
    complexity: 3,
    sfr: 4,
    reps: [5, 12],
    sub: "vertical-push-barbell",
  },
  {
    slug: "barbell-z-press",
    name: "Z-Press",
    pattern: "vertical_push",
    primary: ["front_delts"],
    secondary: ["triceps", "abs", "upper_back"],
    equipment: ["barbell", "weight_plate"],
    load: "barbell",
    compound: true,
    complexity: 4,
    sfr: 3,
    reps: [5, 10],
    sub: "vertical-push-barbell",
    setup: "Seated on the floor, legs straight in a V.",
    cues: "No leg drive available at all, so it exposes any cheating in your press.",
  },
  {
    slug: "dumbbell-overhead-press",
    name: "Dumbbell Overhead Press",
    pattern: "vertical_push",
    primary: ["front_delts"],
    secondary: ["triceps", "side_delts", "abs"],
    equipment: ["dumbbell"],
    load: "dumbbell_pair",
    compound: true,
    complexity: 2,
    sfr: 4,
    reps: [6, 15],
    sub: "vertical-push-dumbbell",
  },
  {
    slug: "seated-dumbbell-press",
    name: "Seated Dumbbell Press",
    pattern: "vertical_push",
    primary: ["front_delts"],
    secondary: ["triceps", "side_delts"],
    equipment: ["dumbbell", "bench_adjustable"],
    load: "dumbbell_pair",
    compound: true,
    complexity: 2,
    sfr: 4,
    reps: [6, 15],
    sub: "vertical-push-dumbbell",
  },
  {
    slug: "arnold-press",
    name: "Arnold Press",
    pattern: "vertical_push",
    primary: ["front_delts", "side_delts"],
    secondary: ["triceps"],
    equipment: ["dumbbell"],
    load: "dumbbell_pair",
    compound: true,
    complexity: 3,
    sfr: 4,
    reps: [8, 15],
    sub: "vertical-push-dumbbell",
  },
  {
    slug: "kettlebell-overhead-press",
    name: "Kettlebell Overhead Press",
    pattern: "vertical_push",
    primary: ["front_delts"],
    secondary: ["triceps", "abs"],
    equipment: ["kettlebell"],
    load: "kettlebell",
    compound: true,
    complexity: 3,
    sfr: 4,
    reps: [5, 12],
    sub: "vertical-push-dumbbell",
  },
  {
    slug: "machine-shoulder-press",
    name: "Machine Shoulder Press",
    pattern: "vertical_push",
    primary: ["front_delts"],
    secondary: ["triceps", "side_delts"],
    equipment: ["chest_press_machine"],
    load: "machine_load",
    compound: true,
    complexity: 1,
    sfr: 5,
    reps: [8, 15],
    sub: "vertical-push-machine",
  },
  {
    slug: "landmine-press",
    name: "Landmine Press",
    pattern: "vertical_push",
    primary: ["front_delts"],
    secondary: ["triceps", "chest", "abs"],
    equipment: ["landmine", "barbell", "weight_plate"],
    load: "barbell",
    unilateral: true,
    compound: true,
    complexity: 2,
    sfr: 4,
    reps: [8, 15],
    sub: "vertical-push-machine",
    cues: "The shoulder-friendly overhead option when full overhead range is uncomfortable.",
  },
  {
    slug: "band-overhead-press",
    name: "Band Overhead Press",
    pattern: "vertical_push",
    primary: ["front_delts"],
    secondary: ["triceps"],
    equipment: ["resistance_band_long"],
    load: "band",
    compound: true,
    complexity: 1,
    sfr: 4,
    reps: [12, 25],
    sub: "vertical-push-bodyweight",
    setup: "Stand on the band, press the handles overhead.",
  },
  {
    slug: "pike-push-up",
    name: "Pike Push-Up",
    pattern: "vertical_push",
    primary: ["front_delts"],
    secondary: ["triceps", "upper_back"],
    equipment: ["bodyweight"],
    load: "bodyweight",
    compound: true,
    complexity: 3,
    sfr: 4,
    reps: [5, 15],
    sub: "vertical-push-bodyweight",
    cues: "The no-equipment overhead press. Hips high, head travels toward the floor between the hands.",
  },
  {
    slug: "elevated-pike-push-up",
    name: "Elevated Pike Push-Up",
    pattern: "vertical_push",
    primary: ["front_delts"],
    secondary: ["triceps"],
    equipment: ["bodyweight", "bench_or_chair"],
    load: "bodyweight",
    compound: true,
    complexity: 4,
    sfr: 4,
    reps: [4, 12],
    sub: "vertical-push-bodyweight",
    cues: "Feet on a chair brings you closer to vertical, so closer to a true overhead press.",
  },
  {
    slug: "handstand-push-up",
    name: "Handstand Push-Up",
    pattern: "vertical_push",
    primary: ["front_delts"],
    secondary: ["triceps", "upper_back", "abs"],
    equipment: ["bodyweight", "wall"],
    load: "bodyweight",
    compound: true,
    complexity: 5,
    sfr: 3,
    reps: [2, 10],
    sub: "vertical-push-bodyweight",
  },
];
