import type { ExerciseSeed } from "../types";

/**
 * Horizontal and vertical pulling.
 *
 * Note on bodyweight-only training: vertical pulling genuinely cannot be loaded
 * without a bar, rings or an anchorable band. That is a real constraint, not a
 * gap in this data — the engine redistributes owed vertical-pull volume to
 * horizontal pull when no option exists. The prone raise variants below exist so
 * that a truly equipment-free session can still train the upper back.
 */

export const HORIZONTAL_PULL: ExerciseSeed[] = [
  {
    slug: "barbell-bent-over-row",
    name: "Barbell Bent-Over Row",
    aliases: ["barbell row", "bent over row"],
    pattern: "horizontal_pull",
    primary: ["lats", "upper_back"],
    secondary: ["biceps", "rear_delts", "lower_back", "forearms"],
    equipment: ["barbell", "weight_plate"],
    load: "barbell",
    compound: true,
    complexity: 3,
    sfr: 3,
    reps: [5, 12],
    sub: "horizontal-pull-barbell",
    cues: "Hinge to roughly 45 degrees and hold it. Pull to the lower ribs, elbows past the torso.",
  },
  {
    slug: "pendlay-row",
    name: "Pendlay Row",
    pattern: "horizontal_pull",
    primary: ["lats", "upper_back"],
    secondary: ["biceps", "rear_delts", "traps"],
    equipment: ["barbell", "weight_plate"],
    load: "barbell",
    compound: true,
    complexity: 4,
    sfr: 3,
    reps: [4, 10],
    sub: "horizontal-pull-barbell",
    cues: "Dead stop on the floor each rep, torso parallel. No hip English.",
  },
  {
    slug: "barbell-underhand-row",
    name: "Underhand Barbell Row",
    aliases: ["Yates row"],
    pattern: "horizontal_pull",
    primary: ["lats", "upper_back"],
    secondary: ["biceps", "rear_delts"],
    equipment: ["barbell", "weight_plate"],
    load: "barbell",
    compound: true,
    complexity: 3,
    sfr: 3,
    reps: [6, 12],
    sub: "horizontal-pull-barbell",
  },
  {
    slug: "t-bar-row",
    name: "T-Bar Row",
    aliases: ["landmine row"],
    pattern: "horizontal_pull",
    primary: ["lats", "upper_back"],
    secondary: ["biceps", "rear_delts", "traps"],
    equipment: ["landmine", "barbell", "weight_plate"],
    load: "barbell",
    compound: true,
    complexity: 2,
    sfr: 4,
    reps: [8, 15],
    sub: "horizontal-pull-barbell",
  },
  {
    slug: "dumbbell-single-arm-row",
    name: "Single-Arm Dumbbell Row",
    aliases: ["one arm row", "DB row"],
    pattern: "horizontal_pull",
    primary: ["lats", "upper_back"],
    secondary: ["biceps", "rear_delts", "forearms"],
    equipment: ["dumbbell"],
    optional: ["bench_flat", "bench_or_chair"],
    load: "dumbbell_single",
    unilateral: true,
    compound: true,
    complexity: 2,
    sfr: 4,
    reps: [8, 15],
    sub: "horizontal-pull-dumbbell",
    cues: "Brace on a bench or your own knee. Drive the elbow back toward the hip.",
  },
  {
    slug: "chest-supported-dumbbell-row",
    name: "Chest-Supported Dumbbell Row",
    pattern: "horizontal_pull",
    primary: ["upper_back", "lats"],
    secondary: ["biceps", "rear_delts"],
    equipment: ["dumbbell", "bench_adjustable"],
    load: "dumbbell_pair",
    compound: true,
    complexity: 1,
    sfr: 5,
    reps: [8, 15],
    sub: "horizontal-pull-dumbbell",
    cues: "Removes the lower back entirely, so all the fatigue lands on the target muscles.",
  },
  {
    slug: "dumbbell-bent-over-row",
    name: "Dumbbell Bent-Over Row",
    pattern: "horizontal_pull",
    primary: ["lats", "upper_back"],
    secondary: ["biceps", "rear_delts", "lower_back"],
    equipment: ["dumbbell"],
    load: "dumbbell_pair",
    compound: true,
    complexity: 2,
    sfr: 4,
    reps: [8, 15],
    sub: "horizontal-pull-dumbbell",
  },
  {
    slug: "kettlebell-single-arm-row",
    name: "Single-Arm Kettlebell Row",
    pattern: "horizontal_pull",
    primary: ["lats", "upper_back"],
    secondary: ["biceps", "rear_delts"],
    equipment: ["kettlebell"],
    load: "kettlebell",
    unilateral: true,
    compound: true,
    complexity: 2,
    sfr: 4,
    reps: [8, 15],
    sub: "horizontal-pull-dumbbell",
  },
  {
    slug: "renegade-row",
    name: "Renegade Row",
    pattern: "horizontal_pull",
    primary: ["lats", "upper_back"],
    secondary: ["abs", "obliques", "biceps"],
    equipment: ["dumbbell"],
    load: "dumbbell_single",
    unilateral: true,
    compound: true,
    complexity: 3,
    sfr: 3,
    reps: [6, 12],
    sub: "horizontal-pull-dumbbell",
    cues: "Resist rotation. If the hips twist, the weight is too heavy.",
  },
  {
    slug: "seated-cable-row",
    name: "Seated Cable Row",
    pattern: "horizontal_pull",
    primary: ["lats", "upper_back"],
    secondary: ["biceps", "rear_delts"],
    equipment: ["cable_machine"],
    load: "cable_load",
    compound: true,
    complexity: 1,
    sfr: 5,
    reps: [8, 15],
    sub: "horizontal-pull-machine",
  },
  {
    slug: "machine-seated-row",
    name: "Machine Seated Row",
    pattern: "horizontal_pull",
    primary: ["lats", "upper_back"],
    secondary: ["biceps", "rear_delts"],
    equipment: ["row_machine_seated"],
    load: "machine_load",
    compound: true,
    complexity: 1,
    sfr: 5,
    reps: [8, 15],
    sub: "horizontal-pull-machine",
  },
  {
    slug: "cable-face-pull",
    name: "Cable Face Pull",
    pattern: "horizontal_pull",
    primary: ["rear_delts", "upper_back"],
    secondary: ["traps"],
    equipment: ["cable_machine"],
    load: "cable_load",
    complexity: 2,
    sfr: 5,
    reps: [12, 25],
    sub: "rear-delt-upper-back",
    cues: "High volume, low fatigue, and it offsets a lot of pressing. Pull to the forehead, elbows high.",
  },
  {
    slug: "band-face-pull",
    name: "Band Face Pull",
    pattern: "horizontal_pull",
    primary: ["rear_delts", "upper_back"],
    secondary: ["traps"],
    equipment: ["resistance_band_long"],
    load: "band",
    complexity: 1,
    sfr: 5,
    reps: [15, 30],
    sub: "rear-delt-upper-back",
  },
  {
    slug: "inverted-row",
    name: "Inverted Row",
    aliases: ["bodyweight row", "horizontal pull up"],
    pattern: "horizontal_pull",
    primary: ["lats", "upper_back"],
    secondary: ["biceps", "rear_delts", "abs"],
    equipment: ["pullup_bar"],
    optional: ["weight_vest"],
    load: "bodyweight_loaded",
    compound: true,
    complexity: 2,
    sfr: 5,
    reps: [8, 20],
    sub: "horizontal-pull-bodyweight",
    cues: "Body rigid in one line. Raise the feet to make it harder.",
  },
  {
    slug: "ring-row",
    name: "Ring Row",
    pattern: "horizontal_pull",
    primary: ["lats", "upper_back"],
    secondary: ["biceps", "rear_delts", "abs"],
    equipment: ["gymnastic_rings"],
    load: "bodyweight",
    compound: true,
    complexity: 2,
    sfr: 5,
    reps: [8, 20],
    sub: "horizontal-pull-bodyweight",
  },
  {
    slug: "suspension-trainer-row",
    name: "Suspension Trainer Row",
    pattern: "horizontal_pull",
    primary: ["lats", "upper_back"],
    secondary: ["biceps", "rear_delts", "abs"],
    equipment: ["suspension_trainer"],
    load: "bodyweight",
    compound: true,
    complexity: 2,
    sfr: 5,
    reps: [8, 20],
    sub: "horizontal-pull-bodyweight",
  },
  {
    slug: "band-seated-row",
    name: "Band Seated Row",
    pattern: "horizontal_pull",
    primary: ["lats", "upper_back"],
    secondary: ["biceps", "rear_delts"],
    equipment: ["resistance_band_long"],
    load: "band",
    compound: true,
    complexity: 1,
    sfr: 4,
    reps: [12, 25],
    sub: "horizontal-pull-band",
    setup: "Anchor the band at waist height, or loop it around your feet while seated.",
  },
  {
    slug: "band-bent-over-row",
    name: "Band Bent-Over Row",
    pattern: "horizontal_pull",
    primary: ["lats", "upper_back"],
    secondary: ["biceps", "rear_delts"],
    equipment: ["resistance_band_long"],
    load: "band",
    compound: true,
    complexity: 1,
    sfr: 4,
    reps: [12, 25],
    sub: "horizontal-pull-band",
    setup: "Stand on the band, hinge forward, row the ends to the ribs.",
  },
  {
    slug: "table-inverted-row",
    name: "Table Inverted Row",
    aliases: ["under table row"],
    pattern: "horizontal_pull",
    primary: ["lats", "upper_back"],
    secondary: ["biceps", "rear_delts"],
    equipment: ["bodyweight", "bench_or_chair"],
    load: "bodyweight",
    compound: true,
    complexity: 2,
    sfr: 4,
    reps: [8, 20],
    sub: "horizontal-pull-bodyweight",
    setup: "Lie under a sturdy table or desk and grip the edge.",
    cues: "Check it takes your weight before you commit. The only real pulling option in a bare room.",
  },
  {
    slug: "prone-t-raise",
    name: "Prone T-Raise",
    pattern: "horizontal_pull",
    primary: ["rear_delts", "upper_back"],
    secondary: ["traps"],
    equipment: ["bodyweight"],
    optional: ["dumbbell"],
    load: "bodyweight_loaded",
    complexity: 1,
    sfr: 4,
    reps: [12, 25],
    sub: "rear-delt-upper-back",
    setup: "Face down on the floor, arms out to the sides.",
    cues: "Low load by nature, so chase the contraction rather than reps.",
  },
  {
    slug: "prone-y-raise",
    name: "Prone Y-Raise",
    pattern: "horizontal_pull",
    primary: ["upper_back", "rear_delts"],
    secondary: ["traps"],
    equipment: ["bodyweight"],
    optional: ["dumbbell"],
    load: "bodyweight_loaded",
    complexity: 1,
    sfr: 4,
    reps: [12, 25],
    sub: "rear-delt-upper-back",
  },
  {
    slug: "reverse-snow-angel",
    name: "Reverse Snow Angel",
    pattern: "horizontal_pull",
    primary: ["upper_back", "rear_delts"],
    secondary: ["traps"],
    equipment: ["bodyweight"],
    load: "bodyweight",
    complexity: 1,
    sfr: 4,
    reps: [10, 20],
    sub: "rear-delt-upper-back",
  },
];

export const VERTICAL_PULL: ExerciseSeed[] = [
  {
    slug: "pull-up",
    name: "Pull-Up",
    aliases: ["pullup", "pull ups"],
    pattern: "vertical_pull",
    primary: ["lats"],
    secondary: ["biceps", "upper_back", "rear_delts", "forearms", "abs"],
    equipment: ["pullup_bar"],
    optional: ["dip_belt", "weight_vest"],
    load: "bodyweight_loaded",
    compound: true,
    complexity: 3,
    sfr: 4,
    reps: [4, 12],
    sub: "vertical-pull-bodyweight",
    cues: "Start from a dead hang. Drive the elbows down and back, chest to the bar.",
  },
  {
    slug: "chin-up",
    name: "Chin-Up",
    pattern: "vertical_pull",
    primary: ["lats", "biceps"],
    secondary: ["upper_back", "forearms"],
    equipment: ["pullup_bar"],
    optional: ["dip_belt", "weight_vest"],
    load: "bodyweight_loaded",
    compound: true,
    complexity: 3,
    sfr: 4,
    reps: [4, 12],
    sub: "vertical-pull-bodyweight",
  },
  {
    slug: "neutral-grip-pull-up",
    name: "Neutral-Grip Pull-Up",
    pattern: "vertical_pull",
    primary: ["lats", "biceps"],
    secondary: ["upper_back", "forearms"],
    equipment: ["pullup_bar"],
    optional: ["dip_belt"],
    load: "bodyweight_loaded",
    compound: true,
    complexity: 3,
    sfr: 4,
    reps: [5, 12],
    sub: "vertical-pull-bodyweight",
    cues: "Usually the kindest grip on the elbows and shoulders.",
  },
  {
    slug: "ring-pull-up",
    name: "Ring Pull-Up",
    pattern: "vertical_pull",
    primary: ["lats"],
    secondary: ["biceps", "upper_back", "forearms"],
    equipment: ["gymnastic_rings"],
    load: "bodyweight_loaded",
    compound: true,
    complexity: 4,
    sfr: 4,
    reps: [4, 12],
    sub: "vertical-pull-bodyweight",
  },
  {
    slug: "negative-pull-up",
    name: "Negative Pull-Up",
    pattern: "vertical_pull",
    primary: ["lats"],
    secondary: ["biceps", "upper_back"],
    equipment: ["pullup_bar"],
    load: "bodyweight",
    compound: true,
    complexity: 2,
    sfr: 4,
    reps: [3, 8],
    sub: "vertical-pull-bodyweight",
    cues: "Jump to the top and lower as slowly as possible. Builds toward full pull-ups.",
  },
  {
    slug: "band-assisted-pull-up",
    name: "Band-Assisted Pull-Up",
    pattern: "vertical_pull",
    primary: ["lats"],
    secondary: ["biceps", "upper_back"],
    equipment: ["pullup_bar", "resistance_band_long"],
    load: "bodyweight_assisted",
    compound: true,
    complexity: 2,
    sfr: 4,
    reps: [6, 15],
    sub: "vertical-pull-bodyweight",
  },
  {
    slug: "assisted-pull-up-machine",
    name: "Assisted Pull-Up (Machine)",
    pattern: "vertical_pull",
    primary: ["lats"],
    secondary: ["biceps", "upper_back"],
    equipment: ["assisted_pullup_machine"],
    load: "bodyweight_assisted",
    compound: true,
    complexity: 1,
    sfr: 5,
    reps: [6, 15],
    sub: "vertical-pull-machine",
  },
  {
    slug: "lat-pulldown",
    name: "Lat Pulldown",
    pattern: "vertical_pull",
    primary: ["lats"],
    secondary: ["biceps", "upper_back", "rear_delts"],
    equipment: ["lat_pulldown"],
    load: "machine_load",
    compound: true,
    complexity: 1,
    sfr: 5,
    reps: [8, 15],
    sub: "vertical-pull-machine",
    cues: "Lets you train the pattern to failure without the fatigue of weighted pull-ups.",
  },
  {
    slug: "neutral-grip-lat-pulldown",
    name: "Neutral-Grip Lat Pulldown",
    pattern: "vertical_pull",
    primary: ["lats"],
    secondary: ["biceps", "upper_back"],
    equipment: ["lat_pulldown"],
    load: "machine_load",
    compound: true,
    complexity: 1,
    sfr: 5,
    reps: [8, 15],
    sub: "vertical-pull-machine",
  },
  {
    slug: "cable-straight-arm-pulldown",
    name: "Straight-Arm Pulldown",
    pattern: "vertical_pull",
    primary: ["lats"],
    equipment: ["cable_machine"],
    load: "cable_load",
    complexity: 2,
    sfr: 5,
    reps: [12, 20],
    sub: "lat-isolation",
    cues: "Isolates the lats without the biceps becoming the limiting factor.",
  },
  {
    slug: "band-straight-arm-pulldown",
    name: "Band Straight-Arm Pulldown",
    pattern: "vertical_pull",
    primary: ["lats"],
    equipment: ["resistance_band_long"],
    load: "band",
    complexity: 1,
    sfr: 5,
    reps: [15, 25],
    sub: "lat-isolation",
  },
  {
    slug: "band-lat-pulldown",
    name: "Band Lat Pulldown",
    pattern: "vertical_pull",
    primary: ["lats"],
    secondary: ["biceps", "upper_back"],
    equipment: ["resistance_band_long"],
    load: "band",
    compound: true,
    complexity: 1,
    sfr: 4,
    reps: [12, 25],
    sub: "vertical-pull-band",
    setup: "Anchor the band over the top of a door or any high fixed point.",
    cues: "The only vertical pull available in most hotel rooms — worth packing a band for.",
  },
  {
    slug: "band-kneeling-pulldown",
    name: "Kneeling Band Pulldown",
    pattern: "vertical_pull",
    primary: ["lats"],
    secondary: ["biceps", "upper_back"],
    equipment: ["resistance_band_long"],
    load: "band",
    compound: true,
    complexity: 1,
    sfr: 4,
    reps: [12, 25],
    sub: "vertical-pull-band",
  },
];
